"""unique_proj_name

Revision ID: 35bc1c36160b
Revises: 94aca1390145
Create Date: 2026-04-17 14:33:45.056355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35bc1c36160b'
down_revision: Union[str, Sequence[str], None] = '94aca1390145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping_columns', 'is_calculated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_mapping_columns_table_id'), table_name='mapping_columns')
    op.drop_index(op.f('idx_mapping_tables_project_id'), table_name='mapping_tables')
    op.create_unique_constraint(None, 'projects', ['name'])
    op.alter_column('rpi_mappings', 'is_calculated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_rpi_mappings_ownership'), table_name='rpi_mappings')
    op.drop_index(op.f('idx_rpi_mappings_project_id'), table_name='rpi_mappings')
    op.drop_index(op.f('idx_rpi_mappings_status'), table_name='rpi_mappings')
    op.drop_index(op.f('idx_rpi_mappings_type'), table_name='rpi_mappings')
    op.alter_column('sources', 'row_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_sources_project_id'), table_name='sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sources_project_id'), 'sources', ['project_id'], unique=False)
    op.alter_column('sources', 'row_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.create_index(op.f('idx_rpi_mappings_type'), 'rpi_mappings', ['measurement_type'], unique=False)
    op.create_index(op.f('idx_rpi_mappings_status'), 'rpi_mappings', ['status'], unique=False)
    op.create_index(op.f('idx_rpi_mappings_project_id'), 'rpi_mappings', ['project_id'], unique=False)
    op.create_index(op.f('idx_rpi_mappings_ownership'), 'rpi_mappings', ['ownership'], unique=False)
    op.alter_column('rpi_mappings', 'is_calculated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index(op.f('idx_mapping_tables_project_id'), 'mapping_tables', ['project_id'], unique=False)
    op.create_index(op.f('idx_mapping_columns_table_id'), 'mapping_columns', ['mapping_table_id'], unique=False)
    op.alter_column('mapping_columns', 'is_calculated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
