"""add_dimension_field_make_measurement_type_nullable

Revision ID: a031b94cecb6
Revises: b5e5857f0d47
Create Date: 2026-04-29 18:37:48.376752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a031b94cecb6'
down_revision: Union[str, Sequence[str], None] = 'b5e5857f0d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpi_mappings', sa.Column('dimension', sa.String(length=255), nullable=True))
    op.alter_column('rpi_mappings', 'measurement_type',
               existing_type=postgresql.ENUM('dimension', 'metric', name='measurementtype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rpi_mappings', 'measurement_type',
               existing_type=postgresql.ENUM('dimension', 'metric', name='measurementtype'),
               nullable=False)
    op.drop_column('rpi_mappings', 'dimension')
    # ### end Alembic commands ###
