"""fastapi_users

Revision ID: ba526ac7dd21
Revises: XXXX_fastapi_users_fields
Create Date: 2026-04-28 10:08:15.374582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba526ac7dd21'
down_revision: Union[str, Sequence[str], None] = 'XXXX_fastapi_users_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_columns', 'type',
               existing_type=postgresql.ENUM('dimension', 'metric', name='columntype_rpi'),
               type_=sa.Enum('dimension', 'metric', name='columntype_rpi'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('source_columns', 'type',
               existing_type=sa.Enum('dimension', 'metric', name='columntype'),
               type_=postgresql.ENUM('dimension', 'metric', name='columntype_rpi'),
               existing_nullable=False)
    # ### end Alembic commands ###
