"""fix_rpi_source_column_fk

Revision ID: cbc528c85f8f
Revises: 002
Create Date: 2026-04-27 18:29:41.681261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbc528c85f8f'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_tables',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_columns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_table_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('type', sa.Enum('dimension', 'metric', name='columntype_rpi'), nullable=False),
        sa.Column('data_type', sa.String(length=64), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_calculated', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('formula', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_tables_source_id'), 'source_tables', ['source_id'], unique=False)
    op.drop_constraint(op.f('fk_sources_mapping_table'), 'sources', type_='foreignkey')
    op.drop_constraint(op.f('rpi_mappings_source_column_id_fkey'), 'rpi_mappings', type_='foreignkey')
    
    op.drop_table('mapping_columns')
    op.drop_table('mapping_tables')
    op.create_foreign_key(None, 'rpi_mappings', 'source_columns', ['source_column_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sources', 'mapping_table_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('mapping_table_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_sources_mapping_table'), 'sources', 'mapping_tables', ['mapping_table_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'rpi_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('rpi_mappings_source_column_id_fkey'), 'rpi_mappings', 'mapping_columns', ['source_column_id'], ['id'], ondelete='SET NULL')
    op.create_table('mapping_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('mapping_tables_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mapping_tables_pkey'))
    )
    op.create_table('mapping_columns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mapping_table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('dimension', 'metric', name='columntype'), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_calculated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('formula', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mapping_table_id'], ['mapping_tables.id'], name=op.f('mapping_columns_mapping_table_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mapping_columns_pkey'))
    )
    op.drop_table('source_columns')
    op.drop_index(op.f('ix_source_tables_source_id'), table_name='source_tables')
    op.drop_table('source_tables')
    # ### end Alembic commands ###
