"""fix_circular_fk

Revision ID: f50fdec921f8
Revises: 4e3b3c8b6212
Create Date: 2026-04-22 13:10:18.449337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f50fdec921f8'
down_revision: Union[str, Sequence[str], None] = '4e3b3c8b6212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping_tables', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mapping_tables', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('mapping_tables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('mapping_tables_source_id_fkey'), 'mapping_tables', type_='foreignkey')
    op.drop_column('mapping_tables', 'source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_tables', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mapping_tables_source_id_fkey'), 'mapping_tables', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.alter_column('mapping_tables', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('mapping_tables', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('mapping_tables', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
